platform :ios, '8.0'

# ignore all warnings from cocoa pods
inhibit_all_warnings!

pod 'XtifyLib', :git => 'https://github.com/giladm/XtifyLib.git', :branch => 'master'

post_install do |installer|
    config = <<-XTIFYGLOBAL_H
    #define xAppKey @"<your app key>"
    #define xLocationRequired NO
    #define xRunAlsoInBackground FALSE
    #define xDesiredLocationAccuracy kCLLocationAccuracyKilometer  // kCLLocationAccuracyBest
    #define xBadgeManagerMethod XLInboxManagedMethod
    #define xLogging TRUE
    #define xNewsstandContent FALSE
    #define xGeofenceEnabled TRUE
    #define xBeaconSupport FALSE
    #define xMultipleMarkets FALSE
    #define xUUID @"REPLACE_WITH_YOUR_UUID"
XTIFYGLOBAL_H
        File.open("Pods/XtifyLib/XtifyLib/XtifyGlobal.h", "w") do |file|
	      file.puts config
	end
end
```
